name: 'RunCyPercyTests_IN'
on: 
  workflow_dispatch:
    inputs:    
      feature:
        description: 'feature to be tested' 
        default: '/**/**/'
      testcases:
        description: 'specify test cases' 
        default: '/*.cy.js'

jobs:  
 ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:
      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
